version:
  tag_prefix_v: true
  components:
    period:
      enabled: true
      initial: 0
    major:
      enabled: true
      initial: 0
    minor:
      enabled: true
      initial: 0
    patch:
      enabled: true
      initial: 0
    timestamp:
      enabled: false
