commits:
  format: "conventional"

version:
  tag_prefix_v: true
  components:
    period:
      enabled: true
      initial: 0
    major:
      enabled: true
      initial: 1
    minor:
      enabled: true
      initial: 0
    timestamp:
      enabled: false

changelog:
  title: "Changelog"
  commit_url: "https://github.com/PanoraGrowth/panora-versioning-pipe-test/commit"

branches:
  development: "development"
  production: "main"
  tag_on: "development"
