#!/bin/sh
# ============================================================================
# Script: update-changelog.sh
# Description: Commit and push changelog to feature/hotfix branch
# Inputs: /tmp/scenario.env, VERSIONING_BRANCH, VERSIONING_PR_ID (env)
# Outputs: Committed and pushed CHANGELOG.md
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "${SCRIPT_DIR}/../lib/common.sh"
. "${SCRIPT_DIR}/../lib/config-parser.sh"

# Load configuration
CHANGELOG_FILE=$(get_changelog_file)
CHANGELOG_TITLE=$(get_changelog_title)
PREPROD_BRANCH=$(get_preprod_branch)
PROD_BRANCH=$(get_production_branch)

# Check if CHANGELOG has changes (modified or new file)
changelog_has_changes() {
    # Check if file is modified
    if ! git diff --quiet "$CHANGELOG_FILE" 2>/dev/null; then
        return 0
    fi
    # Check if file is new (untracked)
    if [ -f "$CHANGELOG_FILE" ] && ! git ls-files --error-unmatch "$CHANGELOG_FILE" >/dev/null 2>&1; then
        return 0
    fi
    return 1
}

# Get list of version files that were modified
get_version_files_modified() {
    if [ -f "/tmp/version_files_modified.txt" ]; then
        cat /tmp/version_files_modified.txt
    fi
}

# Check if any version files were modified
has_version_files_modified() {
    local files=$(get_version_files_modified)
    [ -n "$files" ]
}

# Load scenario
load_env "/tmp/scenario.env"

# Handle development releases
if [ "$SCENARIO" = "development_release" ]; then
    if [ ! -f "/tmp/next_version.txt" ]; then
        exit 0
    fi

    # Check if we have any changes to commit (CHANGELOG, version files, or per-folder changelogs)
    HAS_CHANGELOG_CHANGES=false
    HAS_VERSION_FILES=false
    HAS_PER_FOLDER_CHANGELOGS=false

    if changelog_has_changes; then
        HAS_CHANGELOG_CHANGES=true
    fi

    if has_version_files_modified; then
        HAS_VERSION_FILES=true
    fi

    if [ -f "/tmp/per_folder_changelogs.txt" ] && [ -s "/tmp/per_folder_changelogs.txt" ]; then
        HAS_PER_FOLDER_CHANGELOGS=true
    fi

    if [ "$HAS_CHANGELOG_CHANGES" = "true" ] || [ "$HAS_VERSION_FILES" = "true" ] || [ "$HAS_PER_FOLDER_CHANGELOGS" = "true" ]; then
        log_info "Changes detected - proceeding to commit"
        create_flag "/tmp/proceed_commit.flag"

        NEXT_VERSION=$(read_state "/tmp/next_version.txt")
        BUMP_TYPE=$(read_state "/tmp/bump_type.txt")

        log_section "COMMITTING CHANGES TO FEATURE BRANCH"

        # Stage CHANGELOG
        if [ "$HAS_CHANGELOG_CHANGES" = "true" ]; then
            log_info "Staging: $CHANGELOG_FILE"
            git add "$CHANGELOG_FILE"
        fi

        # Stage version files
        if [ "$HAS_VERSION_FILES" = "true" ]; then
            VERSION_FILES=$(get_version_files_modified)
            for file in $VERSION_FILES; do
                if [ -n "$file" ] && [ -f "$file" ]; then
                    log_info "Staging: $file"
                    git add "$file"
                fi
            done
        fi

        # Stage per-folder changelogs
        if [ "$HAS_PER_FOLDER_CHANGELOGS" = "true" ]; then
            sort -u /tmp/per_folder_changelogs.txt | while IFS= read -r cl; do
                if [ -n "$cl" ] && [ -f "$cl" ]; then
                    log_info "Staging: $cl"
                    git add "$cl"
                fi
            done
        fi

        git commit -m "chore(release): update CHANGELOG for version $NEXT_VERSION ($BUMP_TYPE bump) [skip ci]" \
            -m "" \
            -m "This CHANGELOG will be included in the merge to ${VERSIONING_TARGET_BRANCH}." \
            -m "After merge, the version tag will be created automatically." \
            -m "" \
            -m "Generated by CI Pipeline" \
            -m "Branch: $VERSIONING_BRANCH" \
            -m "PR: #$VERSIONING_PR_ID"

        log_success "Changes committed successfully"
        echo ""

        log_info "Pushing commit to feature branch..."
        git_push_branch "$VERSIONING_BRANCH"

        log_section "PR CHANGELOG GENERATION COMPLETE"
        log_info "Next Version: $NEXT_VERSION"
        log_info "Bump Type:    $BUMP_TYPE"
        echo ""
        log_info "$CHANGELOG_FILE has been added to this PR"
        if [ "$HAS_VERSION_FILES" = "true" ]; then
            log_info "Version files have been updated in this PR"
        fi
        if [ "$HAS_PER_FOLDER_CHANGELOGS" = "true" ]; then
            log_info "Per-folder CHANGELOGs have been updated in this PR"
        fi
        log_info "Review the changes before merging"
    else
        log_info "No changes to commit - already up to date"
        log_info "Pipeline complete (no commit needed)"
    fi
fi

# Handle hotfix scenarios
if [ "$SCENARIO" = "hotfix_to_preprod" ] || [ "$SCENARIO" = "hotfix_to_main" ]; then
    # Check if CHANGELOG exists
    if [ ! -f "$CHANGELOG_FILE" ]; then
        log_info "$CHANGELOG_FILE not found, creating new one..."
        echo "# $CHANGELOG_TITLE" > "$CHANGELOG_FILE"
        echo "" >> "$CHANGELOG_FILE"
    fi

    # Insert hotfix entry at the top (after header)
    sed -i "1r /tmp/hotfix_entry.md" "$CHANGELOG_FILE"

    log_info "$CHANGELOG_FILE updated with hotfix entry"
    echo ""

    # Determine environment name
    if [ "$SCENARIO" = "hotfix_to_preprod" ]; then
        ENV_NAME="$PREPROD_BRANCH"
    else
        ENV_NAME="$PROD_BRANCH"
    fi

    log_section "COMMITTING HOTFIX CHANGELOG"

    git add "$CHANGELOG_FILE"
    git commit -m "chore(hotfix): update CHANGELOG for $ENV_NAME hotfix [skip ci]" \
        -m "" \
        -m "Hotfix applied without version tag." \
        -m "See $CHANGELOG_FILE for details." \
        -m "" \
        -m "Generated by CI Pipeline" \
        -m "Branch: $VERSIONING_BRANCH" \
        -m "PR: #$VERSIONING_PR_ID"

    git_push_branch "$VERSIONING_BRANCH"

    log_section "HOTFIX CHANGELOG UPDATE COMPLETE"
    log_info "Environment: $ENV_NAME"
    log_info "No version tag will be created"
    log_info "$CHANGELOG_FILE has been updated in this PR"
fi
