# Tag on merge to development

name: Development - Create Version Tag

on:
  push:
    branches:
      - development

permissions:
  contents: write

jobs:
  versioning:
    uses: ./.github/workflows/run-versioning.yml
    with:
      branch: development
      commit: ${{ github.sha }}
